version: '3.8'
networks:
    kumu_network:
services: 
    main:
        container_name: kumu_test
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./code:/var/www/html/
        ports:
            - 8000:8000
        networks:
            - kumu_network
    db:
        container_name: kumu_mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'YzzYTr9yRkAZaq'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        networks:
            - kumu_network
    redis:
        container_name: kumu_redis
        image: redis
        restart: always
        ports:
            - '6379:6379'
        expose:
            - '6379'
        networks:
            - kumu_network
    